# Compose schema version
version: '3.3'

# Overriding settings
services:
  reducer:
    volumes:
      - ${HOST_REPO_DIR:-.}/fedn:/app/fedn
      - ${HOST_REPO_DIR:-.}/config/settings-controller.yaml:/app/config/settings-controller.yaml
