name: FEDn Studio Test

on: [push, pull_request]

jobs:
  test-on-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Display Python version
        run: python --version

      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install -r requirements.txt

      - name: Run a simple test script
        run: |
          echo "print('Hello from GitHub Actions on Windows!')" > test_script.py
          python test_script.py
